### ISSUE TITLE
Needed TODO component

### ISSUE THREAD

**Issue by ceremcem** [aktos-io/scada.js#11]
We need basic todo component that will 

- [ ] Create/remove items 
- [ ] Fire events on complete/incomplete
- [ ] Fire events on violating due-date of item 
- [ ] Provide  log in JSON array format

Example usage: 

```pug

todo(
    checklist={{ myChecklist }} 
    log={{ myChecklistLog }} 
    on-completion="myhandler" 
    on-timeout="myTimeoutHandler"
    ) My TODO list HEADER


p some html here 

ul
    +each('myChecklistLog')
        li {{ .event }} {{ .action }} {{ .timestamp }}

```
